"""historia clinica y picture_url

Revision ID: 13eda86686b7
Revises: f3961b6c0207
Create Date: 2026-07-28 15:53:11.630885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13eda86686b7'
down_revision = 'f3961b6c0207'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historia_clinica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('altura_cm', sa.Integer(), nullable=True),
    sa.Column('peso_kg', sa.Float(), nullable=True),
    sa.Column('tipo_sangre', sa.String(length=5), nullable=True),
    sa.Column('alergias_comunes', sa.Text(), nullable=True),
    sa.Column('alergias', sa.Text(), nullable=True),
    sa.Column('enfermedades_comunes', sa.Text(), nullable=True),
    sa.Column('enfermedades', sa.Text(), nullable=True),
    sa.Column('medicamentos', sa.Text(), nullable=True),
    sa.Column('discapacidades', sa.Text(), nullable=True),
    sa.Column('contacto_emergencia_nombre', sa.String(length=120), nullable=True),
    sa.Column('contacto_emergencia_telefono', sa.String(length=20), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historia_clinica')
    # ### end Alembic commands ###
